# Application Configuration
spring.application.name=HR_Frontend

# Server Configuration
server.port=8081

# Backend API URL (without /api/v1 - controllers already have it)
backend.api.url=http://13.205.138.59:8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false    
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
